V = {
"shopkeeper": "{c} apron over shirt|waistcoat, sleeve garters|long {c} coat, scarf|vest, rolled sleeves|w:{c} dress, shawl, apron|m:{c} shirt, braces, cloth cap",
"tavern keeper": "rolled-sleeve shirt, apron|{c} waistcoat, towel on shoulder|leather vest, bare forearms|w:{c} bodice, apron, rolled sleeves|m:open shirt, long apron",
"barmaid": "tavern apron and blouse|{c} vest, bow tie|w:laced {c} bodice, short skirt|w:off-shoulder blouse, apron|m:{c} shirt, long apron|m:waistcoat, rolled sleeves",
"cook": "stained apron, cap|{c} chef coat, neckerchief|rolled sleeves, towel at belt|{c} bandana, apron|tall chef hat, white coat",
"baker": "flour-dusted apron|{c} cap, floury shirt|rolled sleeves, linen apron|w:{c} headscarf, apron dress|m:vest, floury forearms",
"brewer": "leather apron, shirt|{c} work shirt, rolled sleeves|heavy {c} coat, rubber boots|wet canvas apron, boots|{c} waistcoat, cap",
"market seller": "wet apron, boots|{c} oilskin apron|striped shirt, rubber apron|{c} headscarf, long apron|woolly {c} vest, rolled sleeves",
"sea angler": "oilskin coat|{c} sou'wester hat, oilskins|woollen {c} jumper, waders|net over shoulder, shirt|{c} knit cap, jumper",
"sailor": "striped shirt, sash|{c} bandana, open vest|wide-collar {c} shirt, bell trousers|knit {c} cap, pea jacket|sleeveless {c} shirt, rope belt",
"old sailor": "faded jacket, cap|{c} knit jumper, rolled trousers|patched pea jacket|worn captain's {c} coat|oilskin, weathered hat",
"dockworker": "sleeveless vest, trousers|{c} work shirt, braces|leather harness vest, bare arms|canvas apron, cap|torn sleeves, rope belt",
"ferry boatwoman": "wide hat, plain shirt|{c} oilskin, cap|rolled trousers, vest|woolly {c} scarf, jacket|w:headscarf, sleeveless blouse",
"harbour master": "buttoned coat, cap|{c} frock coat, brass buttons|waistcoat, pocket watch|gold-braided coat",
"clerk": "waistcoat, sleeve guards|{c} jacket, cravat|plain shirt, ink-stained cuffs|w:{c} blouse, long skirt|m:{c} suit, round collar",
"scholar": "long robe, scarf|{c} academic gown|tweed coat, cravat|w:{c} high-collar dress|m:waistcoat, loose shirt",
"librarian": "long vest, shirt|{c} cardigan, spectacles chain|shawl, high collar|w:{c} blouse, long skirt|m:waistcoat, bow tie",
"priest": "plain clerical robe|{c} cassock|stole over robe|hooded {c} vestment|plain robe, rope belt",
"nun": "simple habit|{c} hooded habit|plain tunic, rope belt|robe, wooden beads",
"herbalist": "shawl, pouch belt|{c} apron, herb pouches|hooded {c} cloak|w:{c} skirt, vest|m:{c} coat, satchel",
"doctor": "long coat, satchel|white coat, {c} scarf|waistcoat, rolled sleeves|{c} frock coat, spectacles chain|dark coat, stethoscope",
"blacksmith": "scorched leather apron|sleeveless {c} shirt, apron|leather vest, heavy gloves|rolled sleeves, soot-smeared|{c} headband, apron",
"shipwright": "tool belt, work shirt|{c} work jacket, cap|canvas apron, rolled sleeves|vest, sawdust-dusted|bandana, tool pouch",
"carpenter": "work vest, rolled sleeves|{c} overalls|leather apron, pencil in hand|flat cap, canvas apron|tool belt, shirt",
"tailor": "waistcoat, measuring tape|{c} jacket, pins on cuff|apron with pockets|w:{c} dress, tape around neck|m:{c} shirt, braces",
"jeweller": "vest, loupe|{c} brocade waistcoat|jacket, signet rings|dark apron, loupe on forehead",
"bookseller": "long coat, scarf|{c} cardigan|waistcoat, half-moon spectacles|sleeve garters, apron",
"florist": "apron, sun hat|{c} headscarf, apron|rolled sleeves, flower-stained apron|w:{c} dress, apron|m:{c} shirt, apron",
"toymaker": "paint-spotted apron|{c} smock, cap|waistcoat, sawdust|goggles on forehead, apron",
"farmer": "straw hat, work clothes|{c} overalls|patched shirt, braces|w:{c} headscarf, apron dress|m:rolled trousers, vest",
"pasture worker": "wide hat, long coat|{c} poncho|woolly vest, boots|scarf, heavy jacket",
"miner": "dusty overalls, helmet|{c} jacket, headlamp|sooty shirt, braces|leather cap, kerchief",
"lumberjack": "checked shirt, suspenders|{c} flannel, rolled sleeves|sleeveless vest, hat|heavy coat, boots",
"gardener": "apron, gloves|{c} straw hat, smock|rolled trousers, vest|w:{c} dress, apron|m:{c} shirt, braces",
"town watchwoman": "dark coat, cap|{c} greatcoat|leather jerkin, armband|cloak, wide hat",
"Marine officer": "navy-blue uniform coat, no logos|navy-blue coat open, white shirt|navy-blue cap, epaulettes, no logos|navy-blue uniform, sleeves rolled",
"Marine rank-and-file": "navy-blue uniform, no logos|navy-blue striped shirt, cap|navy-blue jacket, rolled sleeves, no logos|navy-blue vest, sailor collar",
"pirate": "open coat, bandana|{c} captain-style coat, sash|ragged striped shirt|tricorn hat, leather vest|bandana, gold hoop earrings",
"smuggler": "hooded cloak, satchel|{c} long coat, scarf|dark vest, hidden pockets|wide hat, travel cloak",
"thug": "sleeveless vest, wrapped fists|{c} leather jacket|torn shirt, studded belt|heavy coat, scarf",
"bounty hunter": "long coat, wide hat|{c} poncho, scarf|dusty long coat|hood, leather vest",
"fortune teller": "beaded shawl, headscarf|{c} robe, many rings|veil, jewelled collar|hooded {c} cloak",
"musician": "loose shirt, sash|{c} waistcoat, cravat|embroidered jacket|bright {c} scarf, vest",
"dancer": "bright skirt, bangles|{c} wrap top, sash, bangles|loose silk trousers, bolero|w:{c} short skirt, bodice|m:{c} open vest, sash",
"street performer": "jester coat|{c} striped vest, hat|patched harlequin outfit|bright mismatched coat",
"hostess": "silk shawl, jewellery|w:{c} evening gown|w:{c} silk dress, gloves|w:{c} corseted dress|m:{c} evening jacket, cravat|m:{c} waistcoat, open collar",
"madam": "fine robe, jewellery|{c} silk gown, fan|embroidered robe, long pipe|velvet {c} dress, long gloves",
"street vendor": "apron, flat cap|{c} vest, rolled sleeves|headscarf, tray strap|patched coat, fingerless gloves",
"innkeeper": "waistcoat, rolled sleeves|{c} apron, key ring|w:{c} dress, apron|m:{c} coat, cravat|cardigan, keys",
"artist": "paint-smeared smock|{c} beret, smock|loose shirt, scarf|stained waistcoat, rolled sleeves",
"navigator": "weathered coat, compass|{c} coat, goggles on forehead|vest, rolled chart|jacket, spyglass at belt",
"village elder": "long robe, shawl|{c} woolly cloak|embroidered vest, cane|patched {c} coat",
"gambler": "waistcoat, rolled sleeves|{c} suit, gold chain|sleeve garters, visor|silk shirt, ring",
"bouncer": "tight dark shirt|{c} sleeveless jacket|leather vest, arms bare|heavy coat, collar up",
"courier": "messenger bag, cap|{c} jacket, satchel|vest, goggles|long {c} coat, boots",
"tattoo artist": "sleeveless top, ink-stained gloves|{c} apron, tattoo sleeves|vest, rolled sleeves|bandana, leather apron",
"bath attendant": "short yukata|{c} tunic, sash|loose robe, tied-back sleeves|towel on shoulder, apron",
"masseuse": "loose tunic|{c} wrap top, trousers|sleeveless robe|short sleeves, apron",
"noble lady": "ornate gown, lace gloves|{c} velvet gown|brocade dress, fan|high-collar silk dress, jewels",
"noble lord": "embroidered frock coat, cravat|{c} velvet coat|silk waistcoat, ruffled shirt|gold-buttoned coat, sash",
"servant": "neat uniform, apron|{c} livery, gloves|w:{c} maid dress, white apron|m:{c} liveried coat",
"housekeeper": "dark formal dress, keys|{c} high-neck dress, apron|w:{c} dress, white collar|m:formal dark coat, white gloves|m:waistcoat, bow tie|m:grey formal jacket, pocket watch",
"beggar": "tattered rags|{c} patched blanket cloak|torn coat, bare feet|layers of rags, scarf",
"washerwoman": "damp apron, rolled sleeves|{c} headscarf, wet dress|bare forearms, wash apron|skirt tied up, apron",
"rope-maker": "leather apron|{c} work shirt, rope belt|vest, rope over shoulder|rolled sleeves, cap",
"net-mender": "worn smock, headscarf|{c} jumper, cap|oilskin apron|rolled trousers, shawl",
"midwife": "clean apron, headscarf|{c} dress, shawl|rolled sleeves, white apron|dark dress, satchel",
"undertaker": "black frock coat|{c} dark coat, top hat|black waistcoat, gloves|long black cloak",
"auctioneer": "striped waistcoat|{c} frock coat, cravat|bright jacket, gavel pocket|bowler hat, coat",
"moneylender": "dark coat, small spectacles|{c} brocade vest|fine coat, ring|sleeve garters, eyeshade",
"fence": "patched coat, many pockets|{c} long coat, scarf|waistcoat, flat cap|hooded cloak",
"forger": "ink-stained cuffs, eyeshade|{c} vest, spectacles|sleeve garters, apron|dark coat, ink-stained fingers",
"chimney sweep": "soot-black overalls|{c} soot-smeared coat, cap|rags, brush|tight cap, sooty shirt",
"lamplighter": "long coat, cap|{c} greatcoat, scarf|vest, pole at shoulder|cloak, lantern on belt",
"mason": "dusty apron, cap|{c} work shirt, leather apron|vest, rolled sleeves|bandana, chalk-covered",
"potter": "clay-smeared apron|{c} smock, headband|rolled sleeves, apron|vest, clay-stained",
"weaver": "plain smock|{c} headscarf, shawl|vest, wool-flecked|w:{c} dress, apron|m:{c} shirt, braces",
}
